function [prompt] = path_exists_prompt(path_name)
%FOLDER_EXIST Summary of this function goes here
%   Detailed explanation goes here

    prompt = sprintf(...
    ['Folder "%s" already exists.\n' ...
     '[Y]es – override it;\n'       ...
     '[N]o – pick another ID;\n'    ...
     '[E]xit – cancel script.\n'    ...
     'Your choice [Y/N/E]: '], path_name);
end
